In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y

array([[1],
       [1],
       [0]])

In [5]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [6]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [9]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [10]:
print(f'X.shape[1]= {X.shape[1]}')
print(f'wh = \n {wh}\n')
print(f'bh = \n {bh}\n')
print(f'wout = \n {wout}\n')
print(f'bout = \n {bout}\n')

X.shape[1]= 4
wh = 
 [[0.17179606 0.8483226  0.84486314]
 [0.97159298 0.89872514 0.83687312]
 [0.5815565  0.32124654 0.7496691 ]
 [0.14542399 0.17425163 0.62646915]]

bh = 
 [[0.79745474 0.85353887 0.55583733]]

wout = 
 [[0.76848089]
 [0.50149121]
 [0.75664847]]

bout = 
 [[0.05185617]]



# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [20]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
    """
    寫出output Layer   
    """
    output_layer_input1 = np.dot( hiddenlayer_activations, wout) 
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.85894158]
 [0.86586942]
 [0.8614401 ]]
wout,bout of Backpropagation:
[[0.76848089]
 [0.50149121]
 [0.75664847]],
[[0.05185617]]


In [21]:
B_wout = derivatives_sigmoid(wout)
B_bout = derivatives_sigmoid(bout)

In [22]:
print ( f"wout of Backpropagation:\n{B_wout}\n")
print ( f"bout of Backpropagation:\n{B_bout}\n")

wout of Backpropagation:
[[0.17791801]
 [0.24999778]
 [0.18413156]]

bout of Backpropagation:
[[0.04916711]]

